### ISSUE TITLE
How to install this library with PHP-8.0 because the documentation say "phpize7.4" ???

### ISSUE THREAD

**Issue by chegmarco1989** [rindow/rindow-openblas#1]
Hello.

The install commands say:

```
$ git clone https://github.com/rindow/rindow-openblas
$ cd rindow_openblas
$ composer update
$ phpize7.4
$ ./configure --enable-rindow_openblas --with-php-config=php-config7.4
$ make clean
$ make
$ make test
```

But can we use `phpize7.4` and `--with-php-config=php-config7.4` when I am currently using **PHP8.0** ???

So how to install `rindow-openblas` with **PHP8.0** ???

Please answer please.

**Comment by yuichiis** [comment]
Thanks for your question.

The current version of this OpenBLAS PHP extension supports PHP 7.2, 7.3, 7.4, 8.0.

Please replace the ~~7.2~~7.4 part in the description with the PHP version you are using and execute each command.

(June 13,2022 Corrected the mistake of writing 7.2)
